### PR TITLE
Online backend experiment

### PR DESCRIPTION
**Pull request by mfkaptan**
This is an online backend experiment as requested in issue #134.

### CODE REVIEW

**Comment by rossant** [comment]
OK it worked the first time here. Can anyone else try it too @rougier @lcampagn @almarklein @Eric89GXL before merging?

**Comment by larsoner** [comment]
@rossant WDYT about porting `experimental` over as a branch in the main repo? I think it would be more convenient than needing to add a separate repo. It would add some overhead to contributions as people would need to make their PRs against the `experimental` branch, but that seems like lower overhead than having to switch between repos...

**Comment by larsoner** [comment]
Works over here. That's neat!

**Comment by larsoner** [comment]
Thanks for the tip about `autobahn` in the readme. I was about to say it didn't work, then I RTFM :)

**Comment by mfkaptan** [comment]
:) I am going to change autobahn with tornado. 
By the way, you can open more than one browser/tab and connect at the same time since server.py is broadcasting the data to all connected js clients. I don't know whether if its useful or not but, you know, this is an experiment.

**Comment by rossant** [comment]
> @rossant WDYT about porting experimental over as a branch in the main repo?

I'd be -1 on this. @almarklein @lcampagn @rougier ? This repo has basically nothing to do with Vispy's code: it just contains random experiments. I'd be even enclined to open 1 repo per idea in the `vispy` group (scenegraph repo, webgl repo, etc.), instead of 1 big experimental repo, but that might be a bit extreme.

**Comment by rossant** [comment]
> By the way, you can open more than one browser/tab and connect at the same time since server.py is broadcasting the data to all connected js clients.

Cool! I can't immediately think about a use case but I'm sure we can come up with something ! :wink:

**Comment by larsoner** [comment]
Ahh, okay. Didn't look closely enough to realize they aren't related -- I can see that they aren't now, though. I'm also -1 on making it a branch then :)

**Comment by almarklein** [comment]
Yes, experimental is also separate to reduce risk of polluting the main repo. The experimental repo is more like a playground :)

**Comment by almarklein** [comment]
I need git help :D  I added mfkaptan as a remote and fetched. I see a few branches, but not this one.

**Comment by rossant** [comment]
add:

fetch = +refs/pull/_/head:refs/remotes/origin/pr/_

under:

[remote "origin"]

in: .git/config

in order to see PR branches

**Comment by almarklein** [comment]
@rossant does that mean I don't even have to add new origins?

**Comment by almarklein** [comment]
Demo works btw. Pretty sweet :)

**Comment by rossant** [comment]
LGTM! Merging.

**Pull request merged**
